### ISSUE TITLE
Implis, Level 13: explain why 'by_cases a : A' does not work

### ISSUE THREAD

**Issue by TentativeConvert** [hhu-adam/Robo#20]
Add branches with these commands, and add hints to these branches.

- After 'intro a',  there's already an assumption called `a`, so using `a` in `by_cases a : A` will rename the existing assumption in an inaccessible way.
- Using `by cases A` will likewise produce inaccesible assumption.

**Comment by joneugster** [comment]
- first point is currently not possible. `Hint` does not care if variables/hypothesis are accessible or not. (although, I guess I could look into implementing such a feature if desired.)
- second point is IMO a bug in Lean and I'll file an issue/PR about `by_cases` ignoring `set_option tactic.hygienic false`

**Comment by TentativeConvert** [comment]
Ah, I forgot that branches catch different proof states and not different commands/tactics.  

But two students made a mistake in this step, out of a very small sample size.  So at least there should be hint saying not to use `by_cases a : A` after `intro a`.  OR, perhaps there should be some explanation earlier about naming assumptions and possible pitfalls.

**Comment by joneugster** [comment]
I added a fixed `by_cases` tactic to the game that deals with both cases:

- if `a` already exists, `by_cases a : A` will create a Hypothesis `a_1 : A`.
- `by cases A` will create a hyp `h : A` (or `h_1 : A` if `h` already exists.)

I'm trying to get this upstreamed, but since `by_cases` is now in Core Lean, PR's might not be as welcome as in Mathlib.

(but even if we keep the modified tactic in the game, besides better naming, it should be the same as the original one, so that should be no issue to the player)
