### ISSUE TITLE
Level 1 crashes when using the recommended `tauto` tactic

### ISSUE THREAD

**Issue by DanielFabian** [hhu-adam/Robo#59]
I tried playing robo and even on the first level 

https://adam.math.hhu.de/#/g/hhu-adam/robo/world/Proposition/level/1

the game immediately crashes and redirects me to a page saying 

```
Oops!
Sorry, an unexpected error has occurred.

(intermediate value)(intermediate value)(intermediate value) is not iterable
```

**Comment by TentativeConvert** [comment]
Sorry for this.  This is probably a version conflict between the game and the server.  I checked that the development version at 

https://adam-dev.math.hhu.de

is up and runnig.  (For the early planets this is identical with the deployed version.)  So you could start playing there until this problem is sorted out.

**Comment by matlorr** [comment]
We updated the robo game and its playable again on https://adam.math.hhu.de/
